jobs:
  job_a:
    description: test
    steps:
      - name: a
        run: echo helloA
      - name: run version
        run: go version
      - name: run version
        run: go build .
      - name: error
        run: not_exist_command
      - name: help
        run: go fmt ./...
        if: which make
  job_b:
    description: test
    steps:
      - name: a
        run: echo helloB
